name: CI
on: [push,pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        choiceL: [--disable-silent-rules, --enable-silent-rules, --enable-debug]
    steps:
      - uses: actions/checkout@v4
      - name: Create configure
        run: |
          sudo apt-get update -y
          sudo apt-get install autoconf automake libtool gcc gimp libgimp2.0-dev
          autoreconf -i
          automake
      - name: Choose configure
        run: ./configure --prefix=/usr ${{ matrix.choiceL }}
      - name: Make gimp-refocus-plugin
        run: make
      - name: Test make strip
        if: matrix.choiceL == '--disable-silent-rules'
        run: make strip
      - name: Test user-level install/uninstall
        if: matrix.choiceL == '--disable-silent-rules'
        run: |
          make install-bin
          make uninstall-bin
      - name: Test 'make install' GIMP shared plugin
        if: matrix.choiceL == '--disable-silent-rules'
        run: |
          sudo make install
          sudo make uninstall
